# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dbb3ea263128cafdb789b2bdac147c4efe8cfb6531400ef44c68bf8ed6d716d8afa07ca89eb8ff635f08ec3fb1053f0ca5e4414a3dbec7ef3d9adace8175fca

test:
  secret_key_base: e0d2ffc225824bfe54ab600295e35d0158764cfbdd40643cfacd9d1f6c1de02dd0f6f1385b2b842635372ea7bdd5d2a2cd0676c3bffc208b884506f6d5c74ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
